#!/bin/sh

set -e

curl http://mfl.s3.amazonaws.com/pub/travis-docker.run > /tmp/travis-docker.run
chmod +x /tmp/travis-docker.run
/tmp/travis-docker.run

sudo echo -e "#!/bin/sh\nexec /tmp/travis-docker/docker -H=tcp://127.0.0.1:2375 $@" > /usr/local/bin/docker
sudo chmod +x /usr/local/bin/docker

sleep 10s
